stages:
  - build
  - publish

default:
  interruptible: true

test:
  stage: build
  image: rust:1.71-bookworm
  services:
    - name: postgres:15
      variables:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
  variables:
    DATABASE: "host=postgres user=postgres password=password"
  before_script:
    - apt update
    - apt install -y cmake
  script:
    - cargo run -p buildsrs-database --features tools --bin migrate
    - cargo test -p buildsrs-database --all-features
    - cargo test -p buildsrs-backend --all-features
    - cargo test -p buildsrs-registry-sync --all-features
    - cargo test -p buildsrs-builder --all-features

backend:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -f backend/Dockerfile -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG
    - docker push "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG"

migrate:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -f database/Dockerfile -t $CI_REGISTRY_IMAGE/migrate:$CI_COMMIT_REF_SLUG
    - docker push "$CI_REGISTRY_IMAGE/migrate:$CI_COMMIT_REF_SLUG"

builder:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -f builder/Dockerfile -t $CI_REGISTRY_IMAGE/builder:$CI_COMMIT_REF_SLUG
    - docker push "$CI_REGISTRY_IMAGE/builder:$CI_COMMIT_REF_SLUG"

registry-sync:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -f backend/Dockerfile -t $CI_REGISTRY_IMAGE/registry-sync:$CI_COMMIT_REF_SLUG
    - docker push "$CI_REGISTRY_IMAGE/registry-sync:$CI_COMMIT_REF_SLUG"

frontend:
  stage: build
  image: rust:1.71-bookworm
  variables:
    TRUNK_VERSION: 0.17.5
  before_script:
    - rustup target add wasm32-unknown-unknown
    - wget -qO- https://github.com/thedodd/trunk/releases/download/v${TRUNK_VERSION}/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf- -C /usr/local/bin
  script:
    - cd frontend && trunk build --release
  artifacts:
    paths:
      - frontend/dist

deploy:
  stage: publish
  image: docker
  variables:
    DOCKER_HOST: ssh://$DEPLOY_HOST
  before_script:
    - mkdir ~/.ssh
    - mv $DEPLOY_KEY ~/.ssh/id_ed25519
    - mv $DEPLOY_HOST_KEY ~/.ssh/known_hosts
    - chmod 0600 ~/.ssh/id_ed25519
  script:
    - docker stack deploy buildsrs --compose-file stack.yml
  only:
    - main
    - prod

pages:
  stage: publish
  image: alpine
  before_script:
    - apk add brotli
  script:
    - export FILES=$(find frontend/dist -type f)
    - gzip -k $FILES
    - brotli -k $FILES
    - mv frontend/dist public
    - echo '/* / 200' >> public/_redirects
  artifacts:
    paths:
      - public
  only:
    - main
