stages:
  - build
  - publish

build:
  stage: build
  image: rust:1.71-bookworm
  variables:
    TRUNK_VERSION: 0.17.5
  before_script:
    - rustup target add wasm32-unknown-unknown
    - wget -qO- https://github.com/thedodd/trunk/releases/download/v${TRUNK_VERSION}/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf- -C /usr/local/bin
  script:
    - cd frontend && trunk build --release
  artifacts:
    paths:
      - frontend/dist

pages:
  stage: publish
  image: alpine
  before_script:
    - apk add brotli
  script:
    - export FILES=$(find frontend/dist -type f)
    - gzip -k $FILES
    - brotli -k $FILES
    - mv frontend/dist public
    - echo '/* / 200' >> public/_redirects
  artifacts:
    paths:
      - public
  only:
    - main
