[workspace]
resolver = "2"
members = [
    "backend",
    "builder",
    "common",
    "database",
    "frontend",
    "protocol",
    "registry-sync",
]

[workspace.dependencies]
buildsrs-database = { path = "./database" }
buildsrs-common = { path = "./common" }
buildsrs-protocol = { path = "./protocol" }
tokio = { version = "1.28.0" }

[workspace.package]
license = "MIT"
# add yourself here if you worked on this
authors = [
    "Patrick Elsen <pelsen@xfbs.net>",
]
