version: "3.8"
services:
  database:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
    volumes:
      - /mnt/postgres_data/pgdata:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.hostname==database
  migrations:
    image: "$CI_REGISTRY_IMAGE/migrate:$CI_COMMIT_REF_SLUG"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname==database
  backend:
    image: "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG"
    command:
      - "sleep 99"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.backend==true


