[package]
name = "buildsrs-backend"
version = "0.1.0"
edition = "2021"
license = { workspace = true }
authors = { workspace = true }

[dependencies]
axum = { version = "0.6.20", features = ["ws"] }
aws-types = "0.56"
aws-credential-types = "0.56"
aws-sdk-s3 = "0.34"
tokio = { version = "1.32.0", features = ["rt-multi-thread"] }
buildsrs-database = { workspace = true }
buildsrs-protocol = { workspace = true }
clap = { version = "4.3.24", features = ["derive", "env"] }
anyhow = "1.0.75"
apply = "0.3.0"
futures = "0.3.28"
thiserror = "1.0.48"
serde_json = "1.0.107"
async-trait = "0.1.74"
bytes = "1.5.0"
url = "2.4.1"
