[package]
name = "buildsrs-database"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
postgres-types = { version = "0.2.5", features = ["derive"] }
rand = "0.8.5"
refinery = { version = "=0.8.9", features = ["tokio-postgres"], optional = true }
strum = { version = "0.24.1", features = ["derive"] }
time = "0.3.21"
tokio = { version = "1.32.0", features = ["macros", "sync", "rt"] }
tokio-postgres = { version = "0.7.8", features = ["with-uuid-1", "with-serde_json-1", "with-chrono-0_4", "with-time-0_3"] }

[dev-dependencies]
refinery = { version = "=0.8.9", features = ["tokio-postgres"] }

[features]
migrations = ["dep:refinery"]

[[bin]]
name = "migrate"
required-features = ["migrations"]
