[package]
name = "buildsrs-common"
version = "0.1.0"
edition = "2021"
license = { workspace = true }
authors = { workspace = true }

[dependencies]
serde = { version = "1.0.185", features = ["derive"] }
url = { version = "2.4.0", features = ["serde"] }
