[package]
name = "buildsrs-common"
edition = "2021"
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
url = { workspace = true, features = ["serde"] }
