[package]
name = "buildsrs-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.31.0", features = ["macros", "rt"] }
tokio-tungstenite = { version = "0.20.0", features = ["rustls-tls-native-roots"] }
buildsrs-protocol = { workspace = true }
clap = { version = "4.4.3", features = ["derive", "env"] }
ssh-key = { version = "0.6.1", features = ["ed25519"] }
url = "2.4.1"
anyhow = "1.0.75"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
